FROM node:22.17.1

WORKDIR /mindforge
COPY . .

ARG NUXT_PUBLIC_CLERK_PUBLISHABLE_KEY
ARG NUXT_CLERK_SECRET_KEY

ENV NUXT_PUBLIC_CLERK_PUBLISHABLE_KEY=$NUXT_PUBLIC_CLERK_PUBLISHABLE_KEY
ENV NUXT_CLERK_SECRET_KEY=$NUXT_CLERK_SECRET_KEY
ENV NUXT_API_URL=http://express:2999/

RUN npm install -g pnpm@9.15.9
RUN pnpm install
RUN pnpm build

EXPOSE 3000

# CMD ["node",".next/standalone/server.js"]
CMD ["node", ".output/server/index.mjs"]

